### ISSUE TITLE
Some important questions about this plugin

### ISSUE THREAD

**Issue by Taxi4you** [transistorsoft/cordova-background-geolocation-lt#1046]
1. Why Android requires paid license?
2. Is this paid once or yearly?
3. Is this code is open source? if Then, why 1?
4. What do you mean by "only need license when not on debug mode"?
Do you mean the debug: BOOLEAN in the configuration of the file that if its set to true so it plays sounds when app goes background?
5. Since this plugin is not free, I have cloned the plugin from mauron to give it a good test, but I got some issues - can you tell me if there those issues here as well:
a. Android when trying to reveal position when not outside - but with very good cellular reception, the user needs to request like 15 times.
b. Android if using stationary event to detect first position, the first position is getting revealed quickly, but then no more locations are received on watch and when user moves to another location, he is stuck on the map on the same place.
c. iOS - not working at background at all.
d. iOS - even when working it works on large bits - dispatch the users position only after 1 min instead of 3 seconds as configured in the plugin.
6. Who supports this plugin? Where are you located, how many employees, how support is going and functioning?
7. If installed the mauron plugin and cordova geolocation plugin in past, how can I remove them manually from the whole project, both on Android and iOS (I have tried to uninstall using cordova cli but seems that it only removed from the config.xml but not from the platforms directories).
8. What are the differences between your plugin to the fork of mauron? Is the fork of mauron is legal? or its a copyright crime?

I would use this plugin for production and need more help in here.
Thanks.

**Comment by christocracy** [comment]
>Why Android requires paid license?

Because most of earth uses Android.  Chances are very high that you're going to release both an iOS and Android version.  I give away iOS free like free drugs, to get you addicted.

>Is this paid once or yearly?

Purchased keys unlock the plugin forever.  You get 1 year access to latest updates / priority support via private Github repo.  Optional yearly fee for another year access to latest updates / priority support is $149 / year.  The public npm version is mirrored from the private version about every 3 months.  Purchased keys will always unlock the public npm verison.

>Is this code is open source?

No.

>What do you mean by "only need license when not on debug mode"?

So you can *try before you buy*.

>Do you mean the debug: BOOLEAN in the configuration of the file that if its set to true so it plays sounds when app goes background?

`debug: true` is helpful when developing so you can *hear* the plugin operating while field-testing, so you don't have to run back to your work-station to determine if it worked or not.

>Since this plugin is not free, I have cloned the plugin from mauron to give it a good test, but I got some issues - can you tell me if there those issues here as well:

Mauron85 version is a fork of my original open-source project from nearly 5 years ago.  My version has evolved significantly over that time.  Any issues with Mauron85 have no correlation.

>Who supports this plugin? Where are you located, how many employees, how support is going and functioning?

This plugin is supported full time for the last 5 years by [Transistor Software](https://www.transistorsoft.com); 3 employees.

>If installed the mauron plugin and cordova geolocation plugin in past, how can I remove them manually from the whole project, both on Android and iOS 

Typical `cordova plugin remove <plugin-name>`.  I'm not involved with instructing you how to remove other plugins we have nothing to do with.

>What are the differences between your plugin to the fork of mauron? Is the fork of mauron is legal? or its a copyright crime?

The differences are vast.  5 years of full time development has occurred since Mauron85 forked my original open source project.  They bear little resemblance anymore.

**Comment by christocracy** [comment]
> Is the fork of mauron is legal? or its a copyright crime?

Mauron85 forked my original open-source project [*when it was open-source*](https://github.com/christocracy/cordova-plugin-background-geolocation).  No, it's not a crime.

**Comment by christocracy** [comment]
And as you’re probably aware by now, you get *very little* support from Mauron85.  With this plugin, support is rapid.

You get what you pay for.

**Comment by christocracy** [comment]
Duplicate #945

**Comment by Taxi4you** [comment]
That sounds very good. I guess I will try to replace and embed your plugin with my code. I hope it will be easy. If I need support, to come here (this github repo on the issues section)?

**Comment by Taxi4you** [comment]
BTW for about the Android license mechanism: how does it work? I buy a serial, put it where?
I mean, detecting the position is something happening in the frontend, so how a serial can be enabled to do so on production?

OR that the serial is just for copyright to make the use legal?

This question is a technical question so I know if I need to know where to put this serial or how this actually working..

**Comment by christocracy** [comment]
> If I need support, to come here

Yes.

>about the Android license mechanism: how does it work?

Everything is well-explained in the [README](https://github.com/transistorsoft/cordova-background-geolocation-lt#large_blue_diamond-configuring-the-plugin).  You don't have to worry, just follow the well-documented instructions.

>so how a serial can be enabled to do so on production?

You're thinking too much about this.  You don't need to be concerned with any of this.  Just follow the directions and everything will just work.
