### ISSUE TITLE
Installation failing if cordova-plugin-background-fetch@6.x is installed

### ISSUE THREAD

**Issue by saoron** [transistorsoft/cordova-background-geolocation-lt#1105]
## Your Environment 
* Plugin version: cordova-background-geolocation-lt@3.4.2
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
Failed to install 'cordova-background-geolocation-lt': CordovaError: Version of installed plugin: "cordova-plugin-background-fetch@6.0.3" does not satisfy dependency plugin requirement "cordova-plugin-background-fetch@~5.6.0"
```

## Expected Behavior
I use the great cordova-plugin-background-fetch plugin on the latest version but it seems to higher then this plugin can accept.

**Comment by christocracy** [comment]
That's right.  `cordova-plugin-background-fetch@~5.6.0` is **incompatible** with `background-geolocation@3.4.2`.  You must install `background-geolocation >= 3.6.0` to use latest `background-fetch` (available now in the private repo only).

**Comment by piotrzuzak** [comment]
Hi @christocracy , We bought your plugin and have the same issue. We've managed to run application downgrading version of cordova-plugin-background-fetch from 6.0.4 to 5.6.0. The problem is probably with recognizing dependencies. Capacitor during installation takes the latest fetch's plugin version instead of declared version in dependencies of your geolocation-lt plugin.xml in node modules.

**Comment by christocracy** [comment]
SInce you're a customer, you should install from the *private* repo https://github.com/transistorsoft/cordova-background-geolocation for latest updates.  The public version from npm is mirrored from the private version only about every 3 months.
