### ISSUE TITLE
Delete a single persisted record

### ISSUE THREAD

**Issue by silver2k** [transistorsoft/cordova-background-geolocation-lt#112]
Hi,

Currently the autoSync/manual sync functionality doesn't meet a clients requirements (Only upload records over a minimum interval - and they want a custom format 😞 ) so I'm investigating writing my own  upload. I'd like the upload to be based on the data persisted in the background, as that looks far more reliable, and allows retries in the event of network outage, etc... 
I can see that I can getLocations - but there doesn't seem to be a way to delete a single location, which I would need to call post-upload. Unless I've missed it?

**Comment by silver2k** [comment]
Just giving this some more thought - The only reason I'm not using sync is because it deletes all the database record *before* I attempt to process them. Thus an error could cause me to lose all my data (significant issue).
However - if sync provided a `done(locations)` callback to the synchronise function, and deleted all the provided locations when `done` was called, this would cover pretty much all cases.

**Comment by christocracy** [comment]
The plugin's database methods are very limited.  You really should allow the plugin to perform http, it's much better at than you are with Ajax, since it already has re-try functionality built-in.  This is particularly important for Android if you care about `stopOnTerminate: false`, since your Javascript is killed when the user closes the app, while the plugin's Android background-service continues to live on, sending locations to the server with its own native HTTP layer.

Your client will have to deal with my schema; there's no mechanism for customizing it.

**Comment by christocracy** [comment]
I'm not really interested in adding complexity to allow people to do http with Ajax, simply because it's pointless to use Ajax for Android when `stopOnTerminate`.

**Comment by christocracy** [comment]
However, it would be relatively trivial to add a `#deleteLocation` method.

**Comment by silver2k** [comment]
Thanks for the response! Well aware I'm stuck between a rock & a hard place here!
