### ISSUE TITLE
Plugin not working in offline mode without internet 

### ISSUE THREAD

**Issue by Ambikapathi** [transistorsoft/cordova-background-geolocation-lt#1223]
## Your Environment
* Plugin version: 3.9.4
* Platform: Android
* OS version: Android 8
* Device manufacturer / model: Vivo 1816
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): android 9.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  BackgroundGeolocation.ready({
          reset: true,
          debug: true,
          logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
          distanceFilter: 5,
          stopTimeout: 1,
          stopOnTerminate: false,
          startOnBoot: true,
         // url: ENV.TRACKER_HOST + '/api/locations',
          // [Android] backgroundPermissionRationale for Always permission.
          backgroundPermissionRationale: {
            title: "Allow Field power to access this device's location even when closed or not in use.",
            message: "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
            positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
            negativeAction: 'Cancel'
          },
          autoSync: true
        }, (state) => {
          console.log('- Configure success: ', state);
          // Update UI state (toggle switch, changePace button)
          this.zone.run(() => {
            this.isMoving = state.isMoving;
            this.enabled = state.enabled;
          });
        });
```

## Expected Behavior
Need Offline background geolocation 

## Actual Behavior
Plugin not working in offline mode

**Comment by christocracy** [comment]
How you *know* it's not working?  This plugin was developed for a disaster response app, tracking first-responders in hurricanes and earthquakes &mdash; it's designed to operate in disconnected environments where the cellular network is assumed to be destroyed.  That's why it has its own SQLite database, so it can record every location locally on the device and upload to server once a network connection is attained.

See Wiki *Debugging* and learn to observe logs from the plugin.
