### ISSUE TITLE
how to increase location accuracy?

### ISSUE THREAD

**Issue by minhk551992** [transistorsoft/cordova-background-geolocation-lt#1237]
I am used to tracking my employee's position, but the position error is sometimes very high. How can I improve my positioning accuracy?
EX:
{
		"event": "motionchange",
		"is_moving": true,
		"uuid": "a5de45df-017f-44b5-b0ee-d26a0883594d",
		"timestamp": "2020-10-27T10:47:42.539Z",
		"odometer": 202.2,
		"coords": {
			"latitude": 21.043954,
			"longitude": 105.755676,
			"accuracy": 1000,
			"speed": 0.01,
			"heading": 319.23,
			"altitude": -1,
			"altitude_accuracy": -1
		},
		"activity": {
			"type": "in_vehicle",
			"confidence": 100
		},
		"battery": {
			"is_charging": false,
			"level": 0.26
		},
		"extras": {}
	}

**Comment by christocracy** [comment]
Ignored issue template.  I have nothing to say until you fill-out the issue template.


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
