### ISSUE TITLE
Disable Significant Change

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/cordova-background-geolocation-lt#148]
Is it possible to disable significant-change on iOS? 

My app requires aggressive tracking from the outset (as soon as a button is pressed). I came across a similar ([issue](https://github.com/christocracy/cordova-plugin-background-geolocation/issues/145)) in the old, none-premium repository where you responded with: 

> See my SampleApp's usage of the #setPace method (via [Aggressive] button)

I can't find the old sample app to see what you were referring to and it doesn't seem to be in the current sample app.

Is this a feature that has now been removed? Is there any way to start tracking immediately using the premium plugin?

Thanks for your time

**Comment by christocracy** [comment]
You need not worry about sig.changes.  The plugin does aggressive monitoring by default.  It uses sig.changes internally.

This doesn't affect you at all.

**Comment by 3rror404** [comment]
Thanks for the swift response. 

Isn't it true that tracking will not start until a cell tower change? I thought this was due to aggressive tracking not being started until a significant change event is detected.

In broad terms my app should work like this:

- Get in vehicle
- Press Start button (`bgGeo.start()`)
- Track location at regular (or elastic) interval
- Press Stop button (`bgGeo.stop()`) at end of journey

My understanding is that between points 2 and 3 we must wait for a cell tower change before aggressive tracking begins.

Have I misunderstood this?

**Comment by christocracy** [comment]
The plugin has 2 states:  **stationary** & **moving**.

When you exec `bgGeo.start()`, iOS immediately enters the **stationary** state.

When iOS is in the **stationary** state, it is monitoring a geofence around the current position (of `stationaryRadius` meters.  iOS has put your app to sleep.

In order to re-awaken, the device must exit the stationary-geofence.  This requires a cell-tower-change event to occur, regardless of your `stationaryRadius`.

When the geofence event triggers, the plugin changes state from **stationary** -> **moving**.  The plugin is not recording a location each `distanceFilter` meters.

You can manually change states with the method `#changePace({Boolean})`.

The only way to improve iOS state-triggering (ie: not relying on celltower-change-event), is to use [preventSuspend: true](https://github.com/transistorsoft/cordova-background-geolocation/tree/master/docs#param-boolean-preventsuspend-false).  Read the warning carefully.

**Comment by 3rror404** [comment]
Sorry, I completely missed the `changePace` section of the readme. 

So immediately after calling `bgGeo.start()` I could call `changePace(true, success, failure)` and this would break out of the geofence and start aggressive tracking straight away?

**Comment by christocracy** [comment]
yes.

I would do it like this:
```js
bgGeo.start(function() {
  bgGeo.changePace(true);
});
```

**Comment by 3rror404** [comment]
Perfect. Thank you. 

I'm going to give this a test tomorrow.
