### ISSUE TITLE
Callback doesn't invoke in background mode (Android)

### ISSUE THREAD

**Issue by wit17** [transistorsoft/cordova-background-geolocation-lt#172]
If close app then callback code in bgGeo.onLocation, bgGeo.onHeartbeat stop working.
OS Android. Real device and emulator.

**Comment by christocracy** [comment]
That's correct.  When user closes app, the foreground Activity, where you Javascript lives (and **dies**), is completely destroyed.

The plugin's BackgroundService lives on, completely unaffected.  This is why it's crucial to configure the plugin's native HTTP layer so that it can continue to POST locations to your server.

There are a number of `forceReloadOnX` (see docs) config params which can actually re-launch the foreground Activity, bringing your Javascript alive again.  Your app will briefly come to the foreground before immediately minimizing.
