### ISSUE TITLE
how to get BG service to execute callbacks on Android when app is closed?

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#223]
When app is closed no callbacks are executed. Is there a hook for code(native?) to be executed for the various #on events?

## Your Environment
* Plugin version: 2.2.0
* Platform: Android
* OS version: 5.1.1
* Device manufacturer / model: Nexus 4
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin config
startOnBoot: true
stopOnTerminate: false
foregroundService: true

**Comment by christocracy** [comment]
When the user closes an Android app, your Cordova app is completely destroyed and won't be automatically re-awakened.  Only the plugin's pure native background-service continues to live on, "headless".  This is why it's crucial you provide an `#url` to the plugin, so that the native background service can continue posting locations to your server.

You may use the [`forceReloadOn*`](https://github.com/transistorsoft/cordova-background-geolocation-lt/tree/master/docs#param-boolean-forcereloadonmotionchange-false) config params to **reload** your Cordova app to service particular events in your Javascript callback.

**Comment by JohnyBoy1234** [comment]
Okay thanks!
