### ISSUE TITLE
Working bad when in the background

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#231]
The plugin is not running any background task. I'm trying to run a "sync" within the "onlocation" event, but it only runs if it's in the foreground. I am able to send the coordinates only when I configure autosync = true, which I do not want.
I even hear the sounds of the events "onlocation" happening in the background with debug = true, but it does not execute the "sync" I programmed.
  I'm using Android.

**Comment by christocracy** [comment]
Do not ignore the **issue template** if you don't want me to ignore your issue.  I will re-open this issue after you provide the following information:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
