### ISSUE TITLE
Depricated API?

### ISSUE THREAD

**Issue by netomia** [transistorsoft/cordova-background-geolocation-lt#233]
When I try to build my Cordova 6 app for Android with this plugin, I get this error:

"Note: Some input files use or override a deprecated API."

This happens only when I add this plugin.

My Android SDKs are all up to date.

* Plugin version: 2.2.0
* Platform: Android
* OS version: 6
* Device manufacturer / model: Several
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 6.0.0

**Comment by christocracy** [comment]
It's fine.  Ignore it

**Comment by netomia** [comment]
Sorry, I should clarify. This situation seems to cause a fatal error in my googlemaps plugin. Here is my entire build error section:

--------

Error: cmd: Command failed with exit code 1 Error output:
C:\.....\platforms\android\src\plugin\google\maps\PluginUtil.java:135: error: cannot access AbstractSafeParc
elable
    Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by netomia** [comment]
The app builds fine with googlemaps when I remove this plugin.

**Comment by christocracy** [comment]
The warning you see is most likely caused by the plugin's use of the permission:
```xml
<uses-permission android:name="android.permission.GET_TASKS" />
```
![](https://www.dropbox.com/s/qdnnz9gzk3i58hv/Screenshot%202016-12-06%2007.53.47.png?dl=1)

This has **nothing** to do with your issue.

While deprecated, the plugin uses it for a method with a subset of behaviour guaranteed for backwards-compatibility.
https://developer.android.com/reference/android/app/ActivityManager.html#getRecentTasks(int,%20int)
>This method was deprecated in API level 21.
As of LOLLIPOP, this method is no longer available to third party applications: the introduction of document-centric recents means it can leak personal information to the caller. **For backwards compatibility, it will still return a small subset of its data: at least the caller's own tasks**

It's precisely these **caller's own tasks** which the plugin needs to know about, specifically the `MainActivity`, so the plugin can know if the user terminated the app.

This is **nothing** to do with your issue.

The problem is with the googlemaps plugin.  For one thing, [they **PIN** their `play-services-location` dependency at `9.8.0`](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L49).  Why should *their* plugin be the authority on which version of `play-services` must be installed?  If I had a dollar for every plugin that made this mistake...

My plugin [does not make such an assumption](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/build.gradle#L9).  It does **not** pin a play-services version.
```
compile 'com.google.android.gms:play-services-location:+' 
```


I suggest you [search their issues](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1208) and complain to them.

**Comment by netomia** [comment]
Thank you for your informative response and solution :)

**Comment by joewoodhouse** [comment]
A quick question on this topic if you don't mind. 

So your plugin (correctly) sets the version at '+' meaning that it will use the SDK related to the latest version of google play services at build time. So for example at the time of writing this is about version 11 something.

If I run the app on a device that has a version of google play services prior to 11, I get this error when running the app:
```
Google Play services out of date.  Requires 11010000 but found 8703438
```
The requirement presumably comes from the version built into the app. There is no warning to the user when installing the app that their version of play services is out of date, so the app just fails silently.

I've read through your thoughts on the cordova-google-maps plugin issue, but I can't really see how this particular point is addressed. If you say "you must have at least the version of google play services that I built this app with", and there is no warning when users with older versions try to use the app, it seems quite unsustainable?

**Comment by christocracy** [comment]
A popup is supposed to appear prompting the user to update Google Play Services.  That doesn't occur?

**Comment by christocracy** [comment]
[This is supposed to run](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/src/android/CDVBackgroundGeolocation.java#L1014) when play-services fails to connect.
