### ISSUE TITLE
Is there a forceReloadOnSchedule ?

### ISSUE THREAD

**Issue by JohnyBoy1234** [transistorsoft/cordova-background-geolocation-lt#237]
The docs show forceReloadOnMotionChange, forceReloadOnGeofence etc. but there doesn't seem to be forceReloadOnSchedule
Is that on purpose?

## Your Environment
Plugin version: 2.2.0
Platform: Android
OS version: 5.1.1
Device manufacturer / model: Nexus 4
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): android 6.0.0
Plugin config
startOnBoot: true
stopOnTerminate: false
foregroundService: true

**Comment by christocracy** [comment]
Nobody asked for it.  One of the Premium customers asked for it too yesterday.  I'll add probably add it next week, though it won't end up here on the Free side for a while longer, since the Free side only gets the latest stable release.  Only [Premium access](http://www.transistorsoft.com/shop/products/cordova-background-geolocation#plans) gets you the latest updates.

**Comment by JohnyBoy1234** [comment]
Okay sounds good

**Comment by christocracy** [comment]
This has been implemented.
