### ISSUE TITLE
Proper configuration for tracking a walk

### ISSUE THREAD

**Issue by andistancu** [transistorsoft/cordova-background-geolocation-lt#242]
Hi,

I'm trying to track a walk. I'm doubting what's the best configuration of the plugin considering that I might stop and sit a bench. It can be that I stop for 2 minutes, or for an hour. What is the proper (battery friendly) way to configure this?

The issues I've encountered in my multiple configuration tests:
- I stop for a little bit. Then I appear after a long time in a very distant place.
- When I walk in a straight line I appear jumping from one side of the sidewalk to the other.

I use all the geo submissions to calculate the distance walked (server side). jumping from one side to the other of the sidewalk greatly increases the distance walked.

The "best" configuration I got so far:

```
		        desiredAccuracy: 0,
		        distanceFilter: 5,
		        stationaryRadius: 3,
		        locationUpdateInterval: 1000,
		        fastestLocationUpdateInterval: 500,
		
		        // Activity Recognition config
		        activityType: 'Fitness',
		        activityRecognitionInterval: 1000,
		        pausesLocationUpdatesAutomatically: false,
		        stopDetectionDelay: 10,
		        disableStopDetection: true,
		        stopTimeout: 240,
		
		        // Application config
		        debug: true,
		        stopOnTerminate: true,
		        startOnBoot: false,
		
		        // HTTP / SQLite config
		        url: '',
		        method: 'POST',
		        autoSync: true,
		        maxDaysToPersist: 1,
```

I also played around with changePace() but I guess I didn't understand exactly how this one works.

Thank you.

Attachment
![img_0154](https://cloud.githubusercontent.com/assets/5528106/21327742/dda993b0-c630-11e6-9894-fe0503cb6248.PNG)
: screenshot of zigzag walking

**Comment by christocracy** [comment]
The plugin has 2 states:  **stationary** and **moving**.  The plugin automatically switches between these states.

`#changePace` is a manual override to perform a state-change.

I would not set a `stopTimeout` greater than 15 minutes.  iOS will require the user to **move ~200 meters** before the plugin performs a state-change to **moving**.  Over a distance of several km, this is negligible.

## iOS `preventSuspend` mode.
For iOS, you might also try using `preventSuspend: true` during a route.  This will leave your app code running in the background constantly and the plugin will detect motion-changes **very** rapidly using the M7 chip's accelerometer-based API.  **WARNING**:  do **NOT** leave the plugin *constantly* configured for `preventSuspend: true` since it prevents iOS from suspending the app and will drain more battery power.  Use it **only** during a walk and turn it off by re-configuring to `preventSuspend: false` when the walk is complete.  With `preventSuspend: true`, `stopTimeout` becomes un-important and you can safely set it to `0` or `1`.

Android is much better in the regard, requiring about 5-10 meters of movement before it triggers tracking.  Android is always monitoring an accelerometer-based api.

**Comment by andistancu** [comment]
Hi @christocracy and thank you for your response.

I see now that stopTimeout is defined in minutes, not in seconds. I'll definitively update it for a smaller value.

I will try today your suggestions. But it doesn't seem like it will make my walks more... "straight"? Do you have a solution for that?

Thank you,
Andi Stancu

**Comment by christocracy** [comment]
The "zig-zagging" likely corresponds with poor accuracy.  Other than configuring `desiredAccuracy: 0` (which you have), accuracy is completely dependent upon your device and the network environment.

Also your screenshot looks to be a scale of no more than a few hundred meters.  That's impossible to make any judgement on.  You need to look at km scale.

**Comment by andistancu** [comment]
Hi Chris,

Indeed, the screenshot is zoomed in a lot. I can zoom out, at km scale, and add a glow to the line to make it seem straight, but then the problem is with calculating distance. If I calculate distance in between all these points, I get a walked distance much longer then I actually walked. Going zigzag increases the distance walked 5 times, which makes it completely inaccurate.


Thank you,
Andi Stancu

**Comment by christocracy** [comment]
Native location services are like a tap of water.  The plugin allows you to adjust the "heat" (`desiredAccuracy`) and rate-of-flow (`distanceFilter`).  The plugin holds a cup of water under the tap and delivers this to you.  The water coming out of the tap is completely up to the device, network environment (including satellites in space; obstructions to those satellites).

You've configured `desiredAccuracy: 0`.  There's nothing else the plugin can do for you.

For over 4 years now, I get nothing but superb results from locations all over the world, including [Iceland](http://www.transistorsoft.com/lab/iceland).

**Comment by andistancu** [comment]
I'm sure you do get perfect results, it's just that I can't find a way to get them myself too. I can't get the distance walked, nor a nice route of where I was walking.

The thing is, I'm sure the plugin works 100%, and it's frustrating that I can't get it to work for me.

**Comment by christocracy** [comment]
- Are you testing in a variety of areas or the same place all the time?
- What is the nature of the areas you're testing?
- Where are you located?
- **Show me logs**
- Show me map results

**Comment by christocracy** [comment]
Closed for lack of feedback.
