### ISSUE TITLE
Geofencing: Can we set a maximum accuracy value as part of the geofencing options?

### ISSUE THREAD

**Issue by mb34124** [transistorsoft/cordova-background-geolocation-lt#328]
I've used the plugin and I see a lot of bouncing in and out of geofences.  I have a 50m Geofence and I'm bouncing out with accuracy readings over 2000m.  Is there a way to set a maximum accuracy value that can be used to consider if someone is 'out'?

**Comment by christocracy** [comment]
Please do not ignore the issue template.  I have no idea whether you're talking about iOS or Android.

Update your message with the following information.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by mb34124** [comment]
I'll enter it in the right format but it is irrelevant.  Bouncing in and out of geofences can happen on any device, any version, etc.  This is a documentation question.

**Comment by christocracy** [comment]
and the minimum reliable geofence is ~150 meters.  50 meters is too small (for both iOS and Android)

**Comment by christocracy** [comment]
geofences are handled at the OS level.  There's no way to specify a "maximum accuracy".  You must increase the geofence radius.  It will never work properly with a 50 meter geofence.

**Comment by mb34124** [comment]
With a 150m geofence I would still bounce in and out.  I had accuracy readings of 200m+ and then back down to 6m.  I bounced in and out of the geofence over the course of several minutes.

**Comment by christocracy** [comment]
If your network environment is such that the native location services cannot get a good accuracy fix on your location, your location will "bounce".  There's nothing to be done in this case.

**Comment by mb34124** [comment]
Thanks for answering the question.  We will probably just take the raw location hits and then post process them to remove the 'bounce'.  We've done that before with RFID location data we'll just do it again with GPS data.

**Comment by christocracy** [comment]
In my environment, I have no issues with geofence false triggering.  You need to test geofences in a variety of environments.  

There is no GPS data when you're indoors.  GPS only works outside.  When you're indoors, the location comes from Wifi/Cell tower triangulation.  Locations from Wifi provider are typically 40 meter accuracy.  Cell triangulation typically 1000 meters.

**Comment by mb34124** [comment]
Yes I'm aware of that.  We aren't new to location services.  My example may have been extreme with a 50m geofence, but my point was not.  In a variety of environments you will get bounce.  That is a fact, especially with our customers (indoors and outdoors).  In our use case we must minimize bounce as much as possible.    I was hoping I could minimize bounce through the plugin (and OS apis), but I cannot.  If we are getting 2000m accuracy, the OS really shouldn't be triggering geofence entry or exit events.  It's that simple.

**Comment by mb34124** [comment]
There are 2 methods we have used in the past to solve 'bounce' problems.  1.  Throw out obviously bad data (2000m accuracy).  2.  Use time together with accuracy to filter the raw data and prevent false events from firing.  It's not perfect but certainly makes the data more usable.

**Comment by christocracy** [comment]
There will be some work done in the future for filtering / de-bouncing.  The plugin is responsible for fetching the corresponding trigger location for a particular geofence transition.  The plugin *can* choose to analyze that location and make a decision to not fire the `geofence` event and instead "reset" the geofence by calling `stopMonitoringForRegion` / `startMonitoringForRegion`.

For `entry` transitions, you can possibly debounce by using `notifyOnDwell` with `loiteringDelay` instead of `notifyOnEntry`.
