### ISSUE TITLE
Error in success callback

### ISSUE THREAD

**Issue by creator1134** [transistorsoft/cordova-background-geolocation-lt#366]
I was trying to test the 'providerchange' event provided by the plugin. Got the following error :

Error in Success callbackId: BackgroundGeolocation944880542 : ReferenceError: provider is not defined

**Comment by christocracy** [comment]
There's a reason you're supposed to **not ignore** the issue template:  I have no idea what platform you're talking about:  iOS or Android.



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Closed for failure to use issue template.
