### ISSUE TITLE
How do I get the motion detection

### ISSUE THREAD

**Issue by danielpawel** [transistorsoft/cordova-background-geolocation-lt#378]
We make a test here and we do not identify when the aplication is on foot, or runnning,
Probably because the event **activity change** is not working with us, or maybe we have set it in a wrong way.. 

We made a test put in the log but it don't logged. 

Have any one got this before?

**Comment by christocracy** [comment]
There's a number of reasons you're supposed to complete the issue template. Do not neglect this:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by Didox** [comment]
Hello Cris.

Follow the information below.

::::: Plugin version::::: 
Last version
::::: Platform::::: 
IOS Simulator iPhone 6
::::: OS version::::: 
iPhone 6
:::::cordova::::: 
6.5.0
:::::cordova platform::::
Installed platforms:
  android 6.1.2
  ios 4.3.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
:::::Plugin config::::
{
      desiredAccuracy: 0,
      distanceFilter: 50,
      debug: false, // false on the deploy
      logLevel: 0, // 0 or 1 on the deploy
      foregroundService: true,
      activityRecognitionInterval: 0,
      triggerActivities: 'on_foot, walking, running, in_vehicle',
      notificationTitle: 'Maratona Virtual',
      notificationText: 'Aplicativo rodando em background',
      disableMotionActivityUpdates: false
}

**Comment by christocracy** [comment]
Simulators don't have an accelerometer.  activitychange event doesn't fire in Simulator -- only real devices.

This is why it's important to use the issue template.
