### ISSUE TITLE
General Question - Difference - Evaluation Version vs. Paid Version

### ISSUE THREAD

**Issue by LueTheShoe** [transistorsoft/cordova-background-geolocation-lt#413]
Hi,

I just wanted to ask if there is any difference (except "no Release Build with Evaluation Version") between these versions?
Is the Paid Version more stable/reliable?

I have an issue where the background process (Evaluation Version) stops after approx. 12h of operation. The debug log doesn't show any shutdown of the process.... 

if there is no difference between these versions, I will start a new "Issue" with my exact problem!

Bye!

**Comment by christocracy** [comment]
No there's no difference.  You ignored the issue template so I have no idea what config you're using, Android OS, or model.


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Open a new issue.  Provide the issue template and logs.

**Comment by mgd722** [comment]
Ignoring @LueTheShoe's technical issue, it's still not made clear the difference between the free and paid versions.  Is there a feature comparison somewhere?

**Comment by christocracy** [comment]
Free = iOS only.

License required to unlock Android
