### ISSUE TITLE
Get top priority background tracking on Android

### ISSUE THREAD

**Issue by dbessa1** [transistorsoft/cordova-background-geolocation-lt#448]
I need the background tracking service on Android never to be interrupted, and for this I'm using foregroundService: true. However, even so, I caught my smartphone without notification, and a geofence was not detected.
I wonder if the "notificationPriority" option is related to this. If so, would "NOTIFICATION_PRIORITY_MAX" be able to cause background tracing to never be interrupted? Well I would not want to catch my smartphone blind again to geofences.

**Comment by christocracy** [comment]
Closed for failing to provide issue-template.  Did not provide logs or config.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
