### ISSUE TITLE
I have tried this plugin in xioami(MI note3) mobile, it's not working after I cleared all app from recent task:-(

### ISSUE THREAD

**Issue by trinitymobility123** [transistorsoft/cordova-background-geolocation-lt#455]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
Logs.  Watch `$ adb logcat`, re-produce your issue and post the logs here.

**Comment by christocracy** [comment]
And what about your **plugin config**??

You completely **ignored** the issue template.

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
<!-- include iOS / Android logs
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat

**Comment by christocracy** [comment]
Closed for failing to use issue template (no logs or config)
