### ISSUE TITLE
Geofencing arrow on iOS

### ISSUE THREAD

**Issue by RomanovX** [transistorsoft/cordova-background-geolocation-lt#462]
We are using this plugin solely for (background) geofencing. Therefore an iOS user would expect the app to generate the geofencing arrow (the outline) rather than the location arrow (solid). Is there a way to set the app to provide just that? Or doesn't that work due to the way the plugin works?

**Comment by christocracy** [comment]
No.  The plugin must also monitor the iOS ["Significant Location Changes API"](https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/using_the_significant_change_location_service) in geofences-only mode, in order to [periodically query for new geofences in proximity](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/geofencing.md).
