### ISSUE TITLE
update extra http value

### ISSUE THREAD

**Issue by joe69** [transistorsoft/cordova-background-geolocation-lt#472]
Hi ,

i want to update for each http request the bpm extra parameter. 
I want to send the current heart rate from my polar belt, is this possible ? 

Thanks,
Thomas

**Comment by christocracy** [comment]
How often are you sampling `bpm`?

**Comment by joe69** [comment]
every second.

**Comment by christocracy** [comment]
You can try calling `setConfig({extras: {bpm: bmp}});`.  Whenever a location is recorded, the current `extras` will be appended to each recorded location.

I suggest you attempt to sample `bmp` less-frequently.

**Comment by joe69** [comment]
ok and my last question ,

this is my last question, can i send every 5 seconds a http update when bgGeo.start() till bgGeo.stop()  

thank you;
Thomas

**Comment by christocracy** [comment]
iOS location API is strictly *distance-based*, not *time-based*.

A location is recorded every time the device moves `distanceFilter` meters.

If the device isn't moving, locations are not being recorded.

**Comment by younessAgouzzal** [comment]
Hi, i change extras with setConfig() after the plugin start ,but in my server i dont see any changes

**Comment by K1N5L4Y3R** [comment]
How can something like this (e.g. adding extras obtained from a sensor via Bluetooth which constantly change) be achieved when the app is killed?

I'm guessing I need to manage the background functionality myself because the plugin will only perform "internal" operations when in background (i.e. it will continue tracking and posting locations even if in background, but the rest of my app's code won't run). Am I right?

**Comment by christocracy** [comment]
@K1N5L4Y3R This is not a problem on iOS since iOS always reboots the entire app in the background.  It doesn't have the concept of "running headless" with a Service, like Android.

On Android, you can implement this in native-code via my [`cordova-background-geolocation-broadcast-receiver`](https://github.com/transistorsoft/cordova-background-geolocation-broadcast-receiver) plugin.  In this environment, you can directly access the plugin's native API and respond to any of the plugin's events.
