### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by aniket-kr-joshi** [transistorsoft/cordova-background-geolocation-lt#489]
:compileDebugJava/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:28: error: cannot find symbol
import org.apache.cordova.PermissionHelper;
^
symbol: class PermissionHelper
location: package org.apache.cordova
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:56: error: cannot find symbol
PermissionHelper.requestPermissions(this, 0, permissions);
^
symbol: variable PermissionHelper
location: class Geolocation
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:87: error: cannot find symbol
if(!PermissionHelper.hasPermission(this, p))
^
symbol: variable PermissionHelper
location: class Geolocation
/platforms/android/src/org/apache/cordova/geolocation/Geolocation.java:102: error: cannot find symbol
PermissionHelper.requestPermissions(this, requestCode, permissions);
^
symbol: variable PermissionHelper
location: class Geolocation
/platforms/android/src/nl/xservices/plugins/GooglePlus.java:346: error: cannot find symbol
cordova.getActivity(), acct.getAccount(), true
^
symbol: method getAccount()
location: variable acct of type GoogleSignInAccount
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
FAILED

**Comment by christocracy** [comment]
There is an issue template asking you to provide information.

When you **ignore** that, I ignore your issue.

Edit your issue and provide the following information:



## Your Entire vironment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
