### ISSUE TITLE
problem when only using significant changes api

### ISSUE THREAD

**Issue by bohemel** [transistorsoft/cordova-background-geolocation-lt#52]
I'm having trouble using only the significant changes api in iOS. This is how it is configured.

```javascript
window.BackgroundGeolocation.configure(callbackFn, failureFn, {
  useSignificantChangesOnly: true,
  desiredAccuracy: 1000,
  debug: true
});
```

When running the app I get the following error.

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application must support the location background mode (in app's Info.plist, {UIBackgroundModes=(location);}'
```

If I have understood the documentation correctly, when only using the significant change api the app shouldn't have the location background mode enabled.

**Comment by christocracy** [comment]
I'll try it out myself here.

**Comment by greggreenhaw** [comment]
I'm having the same issue when i uncheck location in the background services


016-02-26 11:24:19.953 CRMSuite Mobile[4191:1344001] *** Assertion failure in -[CLLocationManager allowDeferredLocationUpdatesUntilTraveled:timeout:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework/CoreLocation-1861.0.23/Framework/CoreLocation/CLLocationManager.m:844
2016-02-26 11:24:19.965 CRMSuite Mobile[4191:1344001] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application must support the location background mode (in app's Info.plist, {UIBackgroundModes=(location);}'
*** First throw call stack:
(0x181ac9900 0x181137f80 0x181ac97d0 0x18243c99c 0x1883422b8 0x1004fcfe8 0x188344850 0x188340a94 0x18833ae74 0x181a80de4 0x181a8071c 0x181a7eb64 0x1819ad680 0x182ebc088 0x186824d90 0x10009177c 0x18154e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by adde-wik** [comment]
I'm also having this issue, same error message. 

Looked back at an older app I made using this plugin (although older version of iOS and this plugin) and it used to work by setting useSignificantChangesOnly = true and not adding any background modes.

Any news on what might be causing this?

**Comment by adde-wik** [comment]
Just to add some more info to this.

Version 1.21 = Workning
Version 1.3.0 = Failed (with error message mentioned above)
Version 1.3.1 = Workning

**Comment by christocracy** [comment]
I just tested this.  It works as expected.

However, the error you see has been fixed.  It was due to some experimental code I'd accidentally pushed.  It was code for testing deferred location updates.  This has been removed though I think the free repo is due an updated version.

```
016-02-26 11:24:19.953 CRMSuite Mobile[4191:1344001] *** Assertion failure in -[CLLocationManager allowDeferredLocationUpdatesUntilTraveled:timeout:], 
```
