### ISSUE TITLE
Minimal settings for geolocation

### ISSUE THREAD

**Issue by renanmoraes** [transistorsoft/cordova-background-geolocation-lt#543]
## My Environment
* Plugin version: 3.0.0
* Platform: Android
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 6.3.0

## Actual Behavior

I need to know the minimum requirements of the android smartphone to use the plugin.

How many memory?
What processor?
What version of android?

In thesis which smartphone with minimal configuration runs its plugin quiet, I look for something like brand, version, model.

Thank you

**Comment by christocracy** [comment]
Memory / processor doesn't matter for the plugin.  Memory / processor help with rendering a map in your app, but that's not the plugin's concern.

What *does* matter to the plugin are the sensors.  You want a device with all these sensors:
- Gyroscope
- Accelerometer
- Magnetometer
- Significant Motion sensor

My Nexus 4 from 2012 has all these sensors, runs Android 4.3.3 and tracks great.  I typically test with Nexus device (the flagship Android device, where APIs operate as documented).

- A Nexus 5 or 6 work well (if you can find one)
- The google Pixel tracks *really* well but very expensive device.
- Samsung S7 works well.

You don't want a *cheap* device, since these devices typically lower the price by removing sensors (eg: Gyroscope, magnetometer)

**Comment by renanmoraes** [comment]
I need to know in detail what each of these sensors does in the plugin, could you explain me better?

**Comment by christocracy** [comment]
These sensors are used by the [`ActivityRecognitionClient`](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient) from Google Play Services.  This api aggregates motion-data from all the available sensors to determine when the device is `still`, `on_foot`, `in_vehicle`, `on_bicycle`, `running`, etc.

Intelligent tracking by detecting when the device is moving / stationary is the primary [Philosophy of Operation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation)
