### ISSUE TITLE
Update extras not working

### ISSUE THREAD

**Issue by younessAgouzzal** [transistorsoft/cordova-background-geolocation-lt#544]
I have to update the extras param in the config with new values , i used the setConfig method after starting the plugin but in server side i don't see any changes .

**Comment by christocracy** [comment]
**Do NOT ignore the issues template**.  I have no idea what platform you're talking about.

Update your issue with the following:

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
