### ISSUE TITLE
I'm not getting Json in the format default

### ISSUE THREAD

**Issue by mariobyte** [transistorsoft/cordova-background-geolocation-lt#615]
I'm not getting Json in the format default. 
With file_get_contents ('php: // input');
I'm getting this Json :

Array ( [0] => Array ( [provider] => gps [time] => 1519995296991 [latitude] => -19.6559915 [longitude] => -43.9332339 [accuracy] => 19 [speed] => 1.1100000143051 [altitude] => 812.28002929688 [bearing] => 129.32556152344 [locationProvider] => 0 ) ) 

I do not receive location and params 
I'm getting this error message on the console
"[event] http failure:  Invalid action"

Any tips please ?

**Comment by christocracy** [comment]
Yes, the template is required.

### Provide a general summary of the issue in the Title above 

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
