### ISSUE TITLE
Trying to prevent app kill by Android 

### ISSUE THREAD

**Issue by LarsBocons** [transistorsoft/cordova-background-geolocation-lt#766]
First, if this is not the right place to post questions like this, then please advise me where to direct them.

With Android getting more and more aggressive in their App Killing quest, I'm exploring some features of the BackgroundGeolocation. Our customers are instructed to use our Cordova based app in foreground with power connected, and that has worked fine for years now (they have even worked in the background with the screen turned off). But as of Android 6 (Marshmallow) I have experienced the app being killed by a simple phonecall. This has only happened with no power connected, but I think I need more testing to state that it will only happend with no power connected.

Im now looking at the startBackgroundTask function, which I would implent for Android only. Is there any chance of the risk of OS killing my app would decrease implementing this (given the config I use)? 

Starting from Android 6, I have also noticed my app being killed when opening e.g. Google Maps for directions. In debug mode I hear the service is still running, so could including "forceReloadOnMotionChange" or "forceReloadOnLocationChange" possible get my app going again in this case. I assume it only launches the app if it is not running, right?
This is of course a nice-to-have feature, given our customers are instructed to keep app in foreground.

Regards
Lars B.

## Your Environment
* Plugin version:
* Platform: Android
* OS version: 6+
* Device manufacturer / model: All
* Cordova version (`cordova -v`):
Phonegap version 7.0.1
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin config
{
    "activityRecognitionInterval": 500,
    "allowIdenticalLocations": true,
    "autoSync": true,
    "autoSyncThreshold": 0,
    "batchSync": false,
    "debug": true,
    "deferTime": 0,
    "desiredAccuracy": 0,
    "desiredOdometerAccuracy": 10,
    "disableElasticity": true,
    "disableStopDetection": true,
    "distanceFilter": 0,
    "elasticityMultiplier": 1,
    "enableHeadless": false,
    "extras": {},
    "fastestLocationUpdateInterval": 900,
    "forceReloadOnBoot": false,
    "forceReloadOnGeofence": false,
    "forceReloadOnHeartbeat": false,
    "forceReloadOnLocationChange": false,
    "forceReloadOnMotionChange": false,
    "forceReloadOnSchedule": false,
    "foregroundService": true,
    "geofenceInitialTriggerEntry": true,
    "geofenceProximityRadius": 1000,
    "geofenceTemplate": "",
    "headers": {},
    "headlessJobService": "com.transistorsoft.cordova.bggeo.HeadlessJobService",
    "heartbeatInterval": 30,
    "httpRootProperty": "location",
    "httpTimeout": 60000,
    "isMoving": true,
    "locationTemplate": "",
    "locationTimeout": 60,
    "locationUpdateInterval": 900,
    "locationsOrderDirection": "ASC",
    "logLevel": 0,
    "logMaxDays": 3,
    "maxBatchSize": -1,
    "maxDaysToPersist": 1,
    "maxRecordsToPersist": -1,
    "method": "POST",
    "minimumActivityRecognitionConfidence": 20,
    "notificationColor": "",
    "notificationLargeIcon": "",
    "notificationPriority": 0,
    "notificationSmallIcon": "",
    "notificationText": "Location Service activated",
    "notificationTitle": "",
    "params": {},
    "persist": true,
    "schedule": [],
    "startOnBoot": false,
    "stationaryRadius": 1,
    "stopAfterElapsedMinutes": 0,
    "stopOnStationary": false,
    "stopOnTerminate": true,
    "stopTimeout": 60,
    "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
    "url": "",
    "enabled": true,
    "schedulerEnabled": false,
    "trackingMode": 1,
    "odometer": 56.751007080078125,
    "isFirstBoot": true
}

## Expected Behavior
Trying to keep the app alive.

## Actual Behavior
App being killed by OS when other app is opened and used in foreground.

**Comment by christocracy** [comment]
foregroundService: true is the only thing you can do.

Attempt to reproduce this with a music player app (obviously not via phone call, since that would auto-mute the audio).

A music player runs with the same foreground-service mechanism this plugin does.

The music should not stop playing after app terminate along with aggressive use of other apps.

**Comment by LarsBocons** [comment]
I have two music apps. One is getting killed just by opening chrome, but Spotify seems to survive. Note that when I do my Googles Maps/My app "multitask" test, even Maps (with directions started) will sometimes get killed when my app is in the foreground.

I may have got this wrong, but I view your Background Geolocation plugin as a separate application communicating with my app. My tests have shown that your plugin can run even if my app is killed. So in theory it should be able to launch an app, but that is not what forceReloadOnMotionChange or forceReloadOnLocationChange is for? If not for relauching the plugin-caller-app, what are they for then?

**Comment by christocracy** [comment]
What is the model of the device you're testing on?

>I may have got this wrong, but I view your Background Geolocation plugin as a separate application communicating with my app

It runs as a foreground-service, just as a music-player like Spotify.  Foreground-services are *mostly* immune from OS-termination due to memory pressure.  If there's *extreme* memory pressure, the OS will do what it needs to do in order to support the application currently in focus.

>My tests have shown that your plugin can run even if my app is killed. 

Just like Spotify keeps the music playing.

> forceReloadOnMotionChange

When you terminate an Android app, it's the `MainActivity` which is terminated.  This is where  your Cordova app lives.  When the `MainActivity` is terminated, your Cordova app is terminated.  The plugin's foreground-service lives on.

However, the foreground-service is capable of re-launching the `MainActivity` via a variety of `foreceReloadOnXXX` options.  When your `MainActivity` is *force-launched*, it will briefly appear maximized on-screen before immediately minimizing.

If you're not shy of writing a small bit of Android Java code, you can take advantage of the plugin's new [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) to provide custom behaviour during the *terminated* state, instead of `foreceReloadOnXXX`

**Comment by LarsBocons** [comment]
Thanks, I will keep the headless mode as an last option. First I'll try the foreceReloadOnXXX config option.
I'm testing with phones in the Android Jellybean - Marshmellow range, and only the Marshmellow poses a problem. Guess it will also be problem with later Androids. I wish they would let the user decide when they start an app, something like: "We need to shut down app X in order to free resources, is that OK with you?". With their current scheme, no app can run safely in the background.

**Comment by LarsBocons** [comment]
That was a strange test. Having "forceReloadOnLocationChange": true, didn't get the my app going again. It sounded like it tried (a pause followed by 3-4 fast gps-beeps and log is saying "Forcing main-activity reload"). When I then started my app, it seemed to start yet another service. I stopped gps tracking, but I gues the first service was still running, since I still heard the gps beeps. When I swiped my app away, it was immediately relaunched. So "forceReloadOnLocationChange" had some effect, just not what I was looking for :-)  
I still have the log if you are interested.

**Comment by jumamfa** [comment]
I'm having the same issue is they're anything you could recommend to reduce the possiblity of the 'android app kill' happening

**Comment by christocracy** [comment]
@jumamfa you're not giving me any information.  "me too" is useless.

**Comment by christocracy** [comment]
- Start a music player (eg: Play Music):  start a song playing.
- Terminate the music player app.

Does the song keep playing or does it stop?

>but it's important for us to get our app working on as many devices as possible.

The problem is most likely due to Huawei's aggressive flavour of Android killing services when it's not supposed to.  Nothing I can do.  It's between you and Huawei.
