### ISSUE TITLE
report error ios Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change

### ISSUE THREAD

**Issue by juanjues19** [transistorsoft/cordova-background-geolocation-lt#810]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS 
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 4.5.2
* Plugin config

## Actual Behavior

when we want to up the app to app store, they do not allow it because:

IOS answerd: 
Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change

## Steps to Reproduce

1. the app works good in local environment.

## Context

using tracking when phone is blocked.

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by christocracy** [comment]
My plugin does not use `prefs:root=" non-public URL scheme`.

This is an error commonly reported by the Mauron85 fork of my plugin when attempting to link to the iOS Settings screen for Location Services.

My plugin has always used the **publicly documented** [`UIApplicationOpenSettingsURLString`](https://developer.apple.com/documentation/uikit/uiapplicationopensettingsurlstring?language=objc)
```obj-c
NSURL *settingsURL = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
```

Your error is caused by one of your other plugins.

![](https://dl.dropboxusercontent.com/s/notms3mv49q4eb3/Screenshot%202018-10-22%2012.28.25.png?dl=1)

**Comment by christocracy** [comment]
Your issue is due to [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/262)

**Comment by juanjues19** [comment]
sorry chis i am not a expert , but what plugin is Mauron85, because we do  not use this plugin

**Comment by christocracy** [comment]
>but what plugin is Mauron85, because we do not use this plugin

Forget about it.  It was an *example*.  Your problem is with `cordova-diagnostic-plugin`, __as I said__.

**Comment by juanjues19** [comment]
ok chris, tks for your help and time.
nice day
