### ISSUE TITLE
Cannot find module 'cordova-background-geolocation-lt'.

### ISSUE THREAD

**Issue by ShafiqEssani** [transistorsoft/cordova-background-geolocation-lt#815]
I'm importing this in my sample project and it's not working showing red line. Error: Cannot find module 'cordova-background-geolocation-lt'.

How to fix Chris please help.

**Comment by christocracy** [comment]
I can't help you if you ignore the issue-template:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by madhurakhal** [comment]
I have the same problem.

Plugin Version: 2.13.2
Platform: Android
OS version: 7.0.0
Cordova version: 8.0.0
Cordova platform version : `Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0`

Expected Behaviour:
Should compile easily

Actual Behaviour:
Cannot find module 'cordova-background-geolocation-lt'.



Even I have installed the package from npm.

**Comment by christocracy** [comment]
@madhurakhal `$ cordova plugins`

**Comment by christocracy** [comment]
To syntax highlight *multiple lines*, wrap the code in 3-backticks.

**Comment by madhurakhal** [comment]
```cordova-background-geolocation-lt 2.13.2 "BackgroundGeolocation"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.4 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"```

**Comment by christocracy** [comment]
You know you can **edit your own posts**?
![](https://dl.dropboxusercontent.com/s/fp6ahrvhvxqpi6i/Screenshot%202018-10-27%2012.02.20.png?dl=1)

When in doubt, always first remove / re-add your android platform.
```
$ cordova platform remove android
$ cordova platform add android
```

**Comment by madhurakhal** [comment]
It doesn't solve the problem. I think your package to npm don't have all the files required to act as npm package.
![screen shot 2018-10-27 at 6 05 57 pm](https://user-images.githubusercontent.com/839882/47606383-3a2c0f80-da13-11e8-880c-be8163dcbb21.png)

**Comment by christocracy** [comment]
Show me the Javascript code you're using to access the plugin.

**Comment by madhurakhal** [comment]
`import BackgroundGeolocation from 'cordova-background-geolocation-lt';`

**Comment by christocracy** [comment]
This is your problem.  The README references the latest version `2.14.0-beta.2`.

Typescript functionality is **new** as of last week.

```
$ ionic cordova plugin remove cordova-background-geolocation-lt
$ ionic cordova plugin add cordova-background-geolocation-lt@2.14.0-beta.2 --save
```

**Comment by christocracy** [comment]
Did it work with 2.14.0-beta.2?

**Comment by ShafiqEssani** [comment]
Yes great.
Its working with 2.14.0-beta.2
Thanks Chris.

**Comment by brighittc** [comment]
i Have the same problem with the cordova-background-geolocation-lt 3.4.2. I have the message Uncaught Error: Module cordova-background-geolocation-lt.BackgroundGeolocation does not exist
