### ISSUE TITLE
Ionic 4 - Cannot read property 'onLocation' of undefined TypeError: Cannot read property 'onLocation' of undefined

### ISSUE THREAD

**Issue by zsgithublib** [transistorsoft/cordova-background-geolocation-lt#932]
**Environment**

Plugin version: 3.0.1
Platform: iOS 
OS version: MacOS
Device manufacturer / model: IphoneX
Cordova version (cordova -v): 8.1.2
Cordova platform version (cordova platform ls): ios 4.5.5
Plugin config: ?

**Expected Behavior**

Plugin functions

**Actual Behavior**

Plugin fails to load. Resulting in error: 
TypeError: Cannot read property 'onLocation' of undefined

**Steps to Reproduce**

1.) Create an Ionic 4 application 
2.) Import the attached files
3.) Install the requisite Ionic plugins for the simple map demo
4.) Run ng serve

**Context**

**Debug Logs**

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'onLocation' of undefined
TypeError: Cannot read property 'onLocation' of undefined
    at Function.push../node_modules/cordova-background-geolocation-lt/src/ionic/index.js.BackgroundGeolocation.onLocation (index.js:181)

[Archive.zip](https://github.com/transistorsoft/cordova-background-geolocation-lt/files/3170914/Archive.zip)

**Comment by christocracy** [comment]
No wonder you have problems.  You don’t seem to read directions.

This issue template you deleted is not optional.  It’s **mandatory**.

Edit your issue and provide the following information:

>

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by zsgithublib** [comment]
Edited

**Comment by christocracy** [comment]
The plugin doesn’t exist in the browser via ng serve.

It only works in simulators or real devices.

**Comment by zsgithublib** [comment]
Thank you
