### ISSUE TITLE
Getting late updates of location

### ISSUE THREAD

**Issue by Venkatesh-Veersoftsolutions** [transistorsoft/cordova-background-geolocation-lt#999]
Getting late update events .I have given a time  interval 300000 micro sec . But i am getting updates by 15 min or above 15 min.But where as in Mi mobile i am getting location updates in correct intervals
## Your Environment
* Plugin version:3.0.8
* Platform:  Android
* OS version:7.0
* Device manufacturer / model: Gionee
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`):android 8.1.0
* Plugin config provided to `#ready`: 
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
debug: true,
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
distanceFilter: 0,
locationUpdateInterval: 300000,
startOnBoot: true,
foregroundService: true,
url: url,
autoSync: true,
params: {
tenantId: tenantId,
branchId: branchId,
vsLoginToken: vsLoginToken,
},
allowIdenticalLocations: true,
heartbeatInterval: 300,
stopOnStationary: false,
reset: true
}, (state) => {
console.log('- Configure success: ', state);
this.zone.run(() => {
});
});
```

## Expected Behavior
Location update should be given  within the given interval of time.
## Actual Behavior
Location updates are getting after 15 min of time

## Debug logs

- Android: $ adb logcat
-->
<details>
	<summary>Logs</summary>

**Comment by christocracy** [comment]
I've never heard of a *Gionee* phone but it seems like a low-priced Chinese phone.

See http://dontkillmyapp.com

Also, you're not saving much energy by providing a large `locationUpdateInterval` since the location-services radios are still on for the whole time, witnessed by the presence of the location Icon in the notification bar.  When that icon is on, the device is draining battery.

If you need only *periodic* location, you should configure [`useSignificantChangesOnly: true`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#usesignificantchangesonly)
